# Generated by Django 6.0.3 on 2026-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateField()),
            ],
        ),
    ]
